# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

#### 1. Import NumPy as np

In [1]:
import numpy as np

#### 2. Create an array of 10 zeros 

In [2]:
# CODE HERE
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
# DON'T WRITE HERE

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
# DON'T WRITE HERE

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [5]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
# DON'T WRITE HERE

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Create an array of the integers from 10 to 50

In [6]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
# DON'T WRITE HERE

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Create an array of all the even integers from 10 to 50

In [7]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
# DON'T WRITE HERE

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
np.arange(0, 9).reshape(-1, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# DON'T WRITE HERE

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Create a 3x3 identity matrix

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# DON'T WRITE HERE

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Use NumPy to generate a random number between 0 and 1<br><br>&emsp;NOTE: Your result's value should be different from the one shown below.

In [11]:
np.random.random(1)

array([0.23866837])

In [9]:
# DON'T WRITE HERE

array([0.65248055])

#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution<br><br>&emsp;&ensp;NOTE: Your result's values should be different from the ones shown below.

In [12]:
np.random.randn(25)

array([ 0.0456697 ,  0.5462626 ,  0.89630165,  0.12964499,  0.50299608,
        0.05567903,  1.55452598, -0.45469382, -3.15607433,  1.29847456,
        0.49171353, -0.88204585, -1.96061975,  0.20630321,  0.52073723,
       -0.76384248,  0.13645654,  1.10499589,  0.88250784,  0.12654331,
        0.3230149 ,  2.96943047, -0.04763587, -0.99315207, -0.24231787])

In [10]:
# DON'T WRITE HERE

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 11. Create the following matrix:

In [14]:
np.linspace(1, 100)/100

array([0.01      , 0.03020408, 0.05040816, 0.07061224, 0.09081633,
       0.11102041, 0.13122449, 0.15142857, 0.17163265, 0.19183673,
       0.21204082, 0.2322449 , 0.25244898, 0.27265306, 0.29285714,
       0.31306122, 0.33326531, 0.35346939, 0.37367347, 0.39387755,
       0.41408163, 0.43428571, 0.4544898 , 0.47469388, 0.49489796,
       0.51510204, 0.53530612, 0.5555102 , 0.57571429, 0.59591837,
       0.61612245, 0.63632653, 0.65653061, 0.67673469, 0.69693878,
       0.71714286, 0.73734694, 0.75755102, 0.7777551 , 0.79795918,
       0.81816327, 0.83836735, 0.85857143, 0.87877551, 0.89897959,
       0.91918367, 0.93938776, 0.95959184, 0.97979592, 1.        ])

In [13]:
# DON'T WRITE HERE

#### 12. Create an array of 20 linearly spaced points between 0 and 1:

In [15]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [12]:
# DON'T WRITE HERE

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs:

In [16]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Write code that reproduces the output shown below.<br><br>&emsp;&ensp;Be careful not to run the cell immediately above the output, otherwise you won't be able to see the output any more.

In [18]:
# CODE HERE
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
# DON'T WRITE HERE

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Write code that reproduces the output shown below.

In [19]:
4 * 5

20

In [15]:
# DON'T WRITE HERE

20

#### 15. Write code that reproduces the output shown below.

In [20]:
np.array([2, 7, 12]).reshape(-1, 1)

array([[ 2],
       [ 7],
       [12]])

In [16]:
# DON'T WRITE HERE

array([[ 2],
       [ 7],
       [12]])

#### 16. Write code that reproduces the output shown below.

In [21]:
np.arange(21, 26)

array([21, 22, 23, 24, 25])

In [17]:
# DON'T WRITE HERE

array([21, 22, 23, 24, 25])

#### 17. Write code that reproduces the output shown below.

In [23]:
np.arange(16, 26).reshape(2, -1)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
# DON'T WRITE HERE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy Operations

#### 18. Get the sum of all the values in mat

In [19]:
# DON'T WRITE HERE

325

#### 19. Get the standard deviation of the values in mat

In [20]:
# DON'T WRITE HERE

7.211102550927978

#### 20. Get the sum of all the columns in mat

In [21]:
# DON'T WRITE HERE

array([55, 60, 65, 70, 75])

## Bonus Question
We worked a lot with random data with numpy, but is there a way we can insure that we always get the same random numbers? What does the seed value mean? Does it matter what the actual number is? [Click Here for a Hint](https://www.google.com/search?q=numpy+random+seed)

# Great Job!